name: Notebook Accessibility Scan

on:
  workflow_dispatch:

jobs:
  a11y-scan:
    name: Scan Jupyter Notebooks for Accessibility Issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan notebooks for accessibility issues
        uses: berkeley-dsep-infra/jupyterlab-a11y-checker@main
        with:
          files: "notebooks/**/*.ipynb"
