name: "On-Demand PEP8 Notebook Lint"

on:
  workflow_dispatch:

jobs:
  pep8-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install nbQA and Flake8
        run: |
          python -m pip install --upgrade pip
          pip install nbqa flake8 pylint

      - name: Run PEP8 Linting on Notebooks
        continue-on-error: true
        run: |
          nbqa flake8 notebooks/ --ignore=E402,E203,E265,E501,W291,W293,E261,E226,W504,E123

      - name: Run pylint on notebooks
        continue-on-error: true
        run: |
          nbqa pylint notebooks/ --disable=C0114,C0303,C0301
