## This workflow performs accessibility checks on Jupyter notebooks created or updated in a pull request
name: PR-Triggered Jupyter notebook accessibility check

on:
   pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.ipynb'

jobs:
  Notebook_Accessibility_Check:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/notebook_accessibility_check_pr.yml@new_nb_508_checker
