## This workflow performs PEP8 style checks on the python code in notebook code cells.
name: PR-Triggered Jupyter notebook accessibility check

on:
   pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.ipynb'
      - '*.yml'

jobs:
  Notebook_PEP8_Check:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/notebook_accessibility_check_pr.yml@new_a11y_nb_checker
